name: Deploy Static Portal


on:
  workflow_dispatch:  
  push:
    branches: 
      - main

jobs:
  role1:
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo  
      
    - name: Zip files
      run: zip -qq -r portal-input.zip . -x admin-APIMATIC-BUILD.json

    - name: Call build endpoint
      run: curl -X POST --url 'https://www.apimatic.io/api/portal' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@portal-input.zip' -o portal-output.zip
      
    - name: list 
      run: ls
      
    - name: Extract generated Portal
      run: unzip -qq portal-input.zip -d static-portal
      
    - name: list 
      run: ls
      working-directory: "static-portal"
      
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages publish static-portal --branch=main --project-name=apifiltering


  role2:
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo  
      
    - name: Zip files
      run: zip -qq -r role2-input.zip . -x user-APIMATIC-BUILD.json

    - name: Call build endpoint
      run: curl -X POST --url 'https://www.apimatic.io/api/portal' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@role2-input.zip' -o role2-output.zip
      
    - name: list 
      run: ls
      
    - name: Extract generated Portal
      run: unzip -qq role2-input.zip -d static-portal2
      
    - name: list 
      run: ls
      working-directory: "static-portal2"
      
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages publish static-portal --branch=main --project-name=apifiltering
